---
- name: install gpg
  apt:
    name: gnupg
  when: ansible_distribution == "Ubuntu"

- name: install gpg
  become: no
  homebrew:
    name: gpg-suite
  when: ansible_distribution == "MacOSX"

- name: create user
  user:
    name: "{{ gpg_mame }}"
    state: present
  when: ansible_distribution == "Ubuntu"

- debug: var=gpg_mame

- name: copy authorized_key
  authorized_key:
    user: "{{ gpg_mame }}"
    key: "{{ lookup('file', gpg_ssh_key_file) }}"
  when: ansible_distribution == "Ubuntu"

- name: set fact ansible user gpg_name
  set_fact:
    ansible_user: "{{ gpg_mame }}"

- name: Add gen-key-script
  become: no
  template:
    src: gen-key-script.j2
    dest: /tmp/gen-key-script
  when: gpg_gen_key

- name: gen key
  become: no
  shell: gpg --list-secret-keys {{ gpg_email }} || gpg --batch --gen-key /tmp/gen-key-script
  changed_when: False
  when: gpg_gen_key

- name: create directory for exported keys
  become: no
  file:
    path: "{{ gpg_export_key_dir }}"
    state: directory
  changed_when: False
  loop:
    - "{{ gpg_export_key_dir }}"
    - "{{ gpg_import_key_dir }}"
  when: gpg_export_private_key or gpg_export_public_key or gpg_import_private_key or gpg_import_public_key or gpg_copy_private_key or gpg_copy_public_key

- name: copy GPG private key
  become: no
  copy:
    src: "{{ gpg_copy_private_key_src }}"
    dest: "{{ gpg_copy_private_key_dest }}"
  when: gpg_copy_private_key

- name: copy GPG public key
  become: no
  copy:
    src: "{{ gpg_copy_public_key_src }}"
    dest: "{{ gpg_copy_public_key_dest }}"
  when: gpg_copy_public_key

- name: Import Public GPG Key from file
  become: no
  gpg:
    key_file: "{{ gpg_import_key_dir }}/{{ gpg_public_key_file }}"
  when: gpg_import_public_key

- name: Import Private GPG Key from file
  become: no
  gpg:
    key_file: "{{ gpg_import_key_dir }}/{{ gpg_private_key_file }}"
    key_type: private
    state: latest
  when: gpg_import_private_key

- name: Export Public GPG Key
  become: no
  shell: test -f {{ gpg_export_key_dir }}/{{ gpg_public_key_file }} || gpg --export --armor --output {{ gpg_export_key_dir }}/{{ gpg_public_key_file }} {{ gpg_email }}
  changed_when: False
  when: gpg_export_public_key

- name: Export Private GPG Key
  become: no
  shell: test -f {{ gpg_export_key_dir }}/{{ gpg_private_key_file }} || gpg --export-secret-key --armor --output {{ gpg_export_key_dir }}/{{ gpg_private_key_file }} {{ gpg_email }}
  changed_when: False
  when: gpg_export_private_key

- name: Remove GPG Key
  become: no
  gpg:
    key_id: "{{ {{ gpg_email }} }}"
    state: absent
  when: gpg_remove_key
